version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/FastAPI-Base
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/app-stop.sh
      timeout: 300
      runas: root