services:
  app:
    build: .
    container_name: DhakaCelsius-app-dev
    restart: unless-stopped
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge
