services:
  app:
    build: .
    container_name: fastapi-server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/app
    depends_on:
      - cache
  nginx:
    build: ./nginx/.
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/app/nginx/nginx.conf
    depends_on:
      - app
      - cache

  cache:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis:7.2-alpine
    privileged: true
    command: sh -c "./init.sh"
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data:rw